### ISSUE TITLE
Write to file when running as module

### ISSUE THREAD

**Issue by howardkitto** [gmierz/mindwave-lsl#1]
Hi

I'm trying to run this lib as a module and write the output to a file. Like this...

```
from mindwavelsl import MindwaveLSL

mwlsl = MindwaveLSL('localhost', 13854, './filename.csv')

# Setup the LSL outlet and the ThinkGear connection
mwlsl.setup()

# Run the service
mwlsl.run()
```
The header is written to the file but no data. Am I doing something wrong?

**Comment by gmierz** [comment]
@howardkitto Hi! Sorry for the delay, I completely missed this.

So I think you'll want to do the following:
```
mwlsl = MindwaveLSL('localhost', 13854, file_output_path='mindwave_output', run_lsl=False)
```

The `file_output_path` variable should be a path to a folder, and not an individual file. In the command above, the `mindwave_output` would be the folder the the file with the data gets output to.

If this doesn't help, try adding some print/logging info here to see if there are any samples being produced: https://github.com/gmierz/mindwave-lsl/blob/master/mindwavelsl/outlet.py#L231

Also, it might be possible that the headset isn't returning anything so you should check to see what is happening here: https://github.com/gmierz/mindwave-lsl/blob/master/mindwavelsl/outlet.py#L241

**Comment by gmierz** [comment]
Closing as inactive, @howardkitto please file a new issue if you're still having problems.
